### ISSUE TITLE
Prereq link is dead

### ISSUE THREAD

**Issue by CathyMoya** [MicrosoftDocs/mesh-docs#26] opened 2023-10-22 19:22 UTC
The link at the bottom of the overview page that says Prerequisites is a dead link

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06ff6eac-f9bf-d190-7831-f4c35b09feab
* Version Independent ID: 06ff6eac-f9bf-d190-7831-f4c35b09feab
* Content: [Mesh Development overview](https://learn.microsoft.com/en-us/mesh/develop/development-overview)
* Content Source: [mesh/develop/development-overview.md](https://github.com/MicrosoftDocs/mesh-docs/blob/main/mesh/develop/development-overview.md)
* Service: **mesh**
* GitHub Login: @typride
* Microsoft Alias: **vinnietieto**

**Comment by nmanis** [comment] 2023-10-25 15:28
Thanks Cathy for report.  Duplicate of https://github.com/MicrosoftDocs/mesh-docs/issues/18.   Resolved as of 10/24

**Comment by vtieto** [comment] 2023-11-07 23:48
It's working now.

**Closed by vtieto** 2023-11-07 23:48 UTC
